### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by anthonybaldwin** [jfversluis/HideGoXLRWindow#1]
I wasn't sure where else to send, so figured I'd just create an issue... Seems worth adding this info.:

- You can skip changing Windows execution policy by instead using [Unblock-File](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file?view=powershell-7) on the .ps1 file.
- Another tip is put the .cmd in a folder other than Startup, and instead place a shortcut to the .cmd which is set to open in 'Minimized' mode. Otherwise, that window is open for 30 seconds after the GoXLR window is minimized.

![image](https://user-images.githubusercontent.com/6219998/88484956-5aaa3600-cf27-11ea-90ca-9c717a62b77a.png)

Appreciate the script and instructions!

**Comment by jfversluis** [comment]
Great! Thanks! My PowerShell is a bit rusty and didn't think of that as a solution for the window showing... much appreciated!
